Prevent file overwrite when moving files

diff --git a/fn-case b/fn-case
--- a/fn-case
+++ b/fn-case
@@ -7,6 +7,8 @@
 # -d change directory
 # -f change normal file
 # -r recursive
+# known issues:
+# can not change filename case under MS-Windows
 
 lower=1;
 changedir=0;
@@ -54,9 +56,13 @@ function chFileCase()
 	newpathname=${newpathname%/};
 
 	if [ "$oldname" != "$newname" -a -n "$newname" ]; then
-		mv -f "$oldpathname" "$newpathname" &&
-		echo "$oldpathname --> $newpathname [OK]" ||
-		echo "$oldpathname --> $newpathname [Failed]" >&2
+		if [ ! -e "$newname" ]; then
+			mv -Tn "$oldpathname" "$newpathname" &&
+			echo "$oldpathname --> $newpathname [OK]" ||
+			echo "$oldpathname --> $newpathname [Failed]" >&2
+		else
+			echo "$oldpathname --> $newpathname [Skipped, target exists]" >&2
+		fi;
 	fi;
 }
 
